sudo pacman -S --needed --noconfirm extra/libvlc 
sudo pacman -S --needed --noconfirm extra/phonon-qt6-vlc 
sudo pacman -S --needed --noconfirm extra/playerctl 
sudo pacman -S --needed --noconfirm extra/syncplay 
sudo pacman -S --needed --noconfirm extra/vlc 
sudo pacman -S --needed --noconfirm extra/vlc-cli 
sudo pacman -S --needed --noconfirm extra/vlc-gui-ncurses 
sudo pacman -S --needed --noconfirm extra/vlc-gui-qt 
sudo pacman -S --needed --noconfirm extra/vlc-gui-skins2 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-a52dec 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-aalib 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-alsa 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-aom 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-archive 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-aribb24 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-aribb25 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-ass 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-avahi 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-bluray 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-caca 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-cddb 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-chromecast 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-dav1d 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-dbus 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-dbus-screensaver 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-dca 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-dvb 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-dvd 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-faad2 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-ffmpeg 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-firewire 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-flac 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-fluidsynth 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-freetype 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-gme 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-gnutls 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-gstreamer 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-inflate 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-jack 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-journal 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-jpeg 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-kate 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-kwallet 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-libsecret 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-lirc 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-live555 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-lua 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-mad 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-matroska 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-mdns 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-modplug 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-mpeg2 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-mpg123 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-mtp 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-musepack 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-nfs 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-notify 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-ogg 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-opus 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-png 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-pulse 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-quicksync 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-samplerate 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-sdl 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-sftp 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-shout 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-smb 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-soxr 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-speex 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-srt 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-svg 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-tag 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-theora 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-twolame 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-udev 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-upnp 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-vorbis 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-vpx 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-x264 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-x265 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-xml 
sudo pacman -S --needed --noconfirm extra/vlc-plugin-zvbi 
sudo pacman -S --needed --noconfirm extra/vlc-plugins-all 
sudo pacman -S --needed --noconfirm extra/vlc-plugins-base 
sudo pacman -S --needed --noconfirm extra/vlc-plugins-extra 
sudo pacman -S --needed --noconfirm extra/vlc-plugins-video-output 
sudo pacman -S --needed --noconfirm extra/vlc-plugins-visualization 
