sudo nano /etc/pacman.d/mirrorlist

###############################################################################
################# Arch Linux mirrorlist generated by Reflector #################
################################################################################

# With:       reflector --verbose --age 12 --fastest 10 --score 10 --protocol https --latest 5 --sort rate --save /etc/pacman.d/mirrorlist
# When:       2025-08-15 23:24:01 UTC
# From:       https://archlinux.org/mirrors/status/json/
# Retrieved:  2025-08-15 23:23:41 UTC
# Last Check: 2025-08-15 23:15:23 UTC

Server = https://america.mirror.pkgbuild.com/$repo/os/$arch
